### ISSUE TITLE
Unable to locate package aircrack-ng

### ISSUE THREAD

**Issue by geolimber** [Rajkumrdusad/onex#2]
Can't install aircrack-ng via tool-x and onex. Both tools are updated. Only problem install aircrack-ng

**Comment by Rajkumrdusad** [comment]
Hey @geolimber aircrack-ng is not available for Termux, so you can't install it in termux.

**Comment by Christ441** [comment]
How do I run the installed tools...
Plzzz explain me detaily......for SET,WiFi...etc in onex

**Comment by 1N0XDot** [comment]
1.pkg install root-repo

2.pkg install aircrack-ng

**Comment by 1N0XDot** [comment]
Hey @geolimber  just install root repo:
pkg install root-repo
pkg install aircrack-ng
For me works
