### ISSUE TITLE
new functions

### ISSUE THREAD

**Issue by olegkyka** [Rajkumrdusad/onex#3]
Hi. One request. Make that the category all install. And adding shortcuts to the menu by category.

**Comment by Rajkumrdusad** [comment]
Hey @olegkyka that's very nice suggestion, but its very difficult to install all tools (more then 370+ tools), it take a lots of unnecessary space and take a lost of time to inatall all tools.

**Comment by olegkyka** [comment]
No. For example, all Wireless Testing....

**Comment by Rajkumrdusad** [comment]
Sorry but Category is already exists.

**Comment by olegkyka** [comment]
![Снимок экрана_2020-01-30_17-04-04](https://user-images.githubusercontent.com/37656635/73435296-5095e900-4383-11ea-85b5-0ee1e71a07f6.png)

**Comment by Rajkumrdusad** [comment]
Sorry i did not understand, what the meaning of this 100 ALL, can you explain this.

**Comment by olegkyka** [comment]
100 all= 1+2+3+ .... +30

**Comment by Rajkumrdusad** [comment]
> Hey @olegkyka that's very nice suggestion, but its very difficult to install all tools (more then 370+ tools), it take a lots of unnecessary space and take a lost of time to inatall all tools.

Sorry as i already told you, it's not possible.
